### ISSUE TITLE
Page is blank after archive

### ISSUE THREAD

**Issue by codeliger** [go-shiori/obelisk#37]
Hi I am trying to archive this article

https://www.foodnavigator.com/Article/2022/09/09/study-linking-deaths-to-red-meat-appears-implausible-and-lacks-transparency

`obelisk {above-url}`

Regardless if I use `--no-js` or not it still is blank

Anyone figure out how to get around this?

**Comment by adamkiss** [comment]
@codeliger Looking at the page (and testing it), you'd need to go in, and manually remove the css on `.top-wrapper` that's setting opacity to 0
