### ISSUE TITLE
Borken google.com/about

### ISSUE THREAD

**Issue by mrzv** [go-shiori/obelisk#9]
When I try to download <https://google.com/about>, I get a broken page (missing links, broken formatting, etc.). I'm not sure what's missing, but as a comparison point: when I download the same page with [monolith](https://github.com/Y2Z/monolith), I get a 56MB file vs 53MB with obelisk.

**Comment by waybackarchiver** [comment]
The url https://google.com/about redirected to https://about.google/, I will fix it.
